version: '3'
services:
  client:
    container_name: frontend
    build: ./frontend
    image: frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    #   - ./frontend:/usr/src/app
    networks:
      - mern-app
  
  api:
    container_name: backend
    restart: always
    build: ./backend
    image: api
    ports:
      - "5005:5005"
    stdin_open: true
    tty: true
    volumes:
    - ./backend:/usr/src/app
    - /usr/src/app/node_modules
    env_file:
    - ./backend/.env
    networks:
      - mern-app
    depends_on:
      - database

  database:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - database-data:/data/db

networks:
  mern-app:
    driver: bridge
volumes:
  database-data:
    driver: local
